<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AddressBook;

/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends \Doctrine\ORM\EntityRepository
{
    public static $filterKeys = [
        'firstName',
        'lastName',
        'email',
        'phone',
        'country',
        'city',
        'streetName',
        'streetNumber',
        'zip',
    ];

    /**
     *
     * @param type $adminName
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getAddressBooksList($filterKey = "", $filterValue = "")
    {

        $query = $this->createQueryBuilder('a');
        if ($filterKey && in_array($filterKey, self::$filterKeys) && $filterValue) {
            $query->where("a.$filterKey like :value")
                ->setParameter('value', "%$filterValue%");
        } elseif ($filterValue) {
            foreach (self::$filterKeys as $filterKey) {
                $query->orWhere("a.$filterKey like :value");
            }
            $query->setParameter('value', "%$filterValue%");

        }
        return $query;
    }


}