imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    picture_directory: '%kernel.project_dir%/web/uploads/pictures/'
    page_range: 5
framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
# app/config/config.yml
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../src/AppBundle/Resources/views": View

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path: '%kernel.project_dir%/var/data/data.sqlite'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

liip_imagine:
  # As mentioned above, gd, imagick or gmagick are possible
  driver: "gd"
  default_image: '/uploads/pictures/default.png'
  # This is where all the filters sets are located
  filter_sets:
    cache: []
    square: # The name of the filter, can be later used in the twig template
      quality: 75 # Compression quality, this image will be 75% the quality
      filters:
        thumbnail:
          size: [50, 50]
          mode: outbound
    small:
      quality: 100
      filters:
        relative_resize:
          widen: 350 # Shrink/upscale the image to 800px of height, with full quality
    big:
      filters:
        relative_resize:
          heighten: 800
          allow_upscale: true
knp_paginator:
    template:
        pagination: '@View/pagination.html.twig'
